# 🚗 Car Price Prediction – Regression Model

This project focuses on predicting the price of a car based on its features and specifications using machine learning regression techniques.

The dataset contains information about different cars, such as brand, model, year, mileage, fuel type, transmission, engine characteristics, and other relevant features. 

The goal is to analyze these features and build a machine learning model that can estimate the expected price of a car.

#  Data Exploration

* 📊 Number of rows and columns
* 🔤 Data types
* ❌ Missing values
* 🎯 Target variable: priceUSD
* 🔢 Numerical columns
* ⚠️ Extreme values and outliers
* 📈 Data distribution and potential anomalies

# 📋 Step 1: 
* Import pandas library, Path
* Read and load the dataset
* Info about columns

In [67]:
from pathlib import Path
import pandas as pd

DATA_PATH = Path("../data/cars.csv")

try:
    df = pd.read_csv(DATA_PATH)
    print("---- ✅ Dataset loaded successfully.")
except FileNotFoundError:
    print("Error: The dataset file was not found.")
except pd.errors.EmptyDataError:
    print("Error: The dataset is empty.")
except pd.errors.ParserError:
    print("Error: Failed to parse the dataset.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

df.columns

---- ✅ Dataset loaded successfully.

Index(['make', 'model', 'priceUSD', 'year', 'condition', 'mileage(kilometers)',
       'fuel_type', 'volume(cm3)', 'color', 'transmission', 'drive_unit',
       'segment'],
      dtype='str')

The columns need to be standardize in data_cleaning.

# 📋 Step 2: 
* 📊 Number of rows and columns
* First look at the data

In [68]:
print("Number of rows and columns:",df.shape)
df.sample(5,random_state=42)

Number of rows and columns: (56244, 12)

,make,model,priceUSD,year,condition,mileage(kilometers),fuel_type,volume(cm3),color,transmission,drive_unit,segment
19270,mitsubishi,carisma,2050,1999,with mileage,250000.0,petrol,1800.0,blue,mechanics,front-wheel drive,M
25927,ford,fusion,4500,2006,with mileage,160000.0,petrol,1400.0,burgundy,mechanics,front-wheel drive,M
23388,mercedes-benz,e-klass,3500,1999,with mileage,485000.0,diesel,2900.0,blue,mechanics,rear drive,E
53189,bmw,x3,21000,2013,with mileage,159000.0,diesel,2000.0,black,auto,NaN,J
34058,renault,megane,3990,2002,with mileage,331700.0,diesel,1900.0,other,mechanics,front-wheel drive,C

# 📋 Step 3:
 
* 🔤 Data types
* ❌ Missing values

In [69]:
print("🔍Main Info.")
print("-"*40)
print(df.info())
print("-"*40)
print("----Count Missing Values in dataset:")
print(df.isna().sum())

missing_like_values = ["NaN", "nan", "NULL", "null", "None", "none", "", " "]
 
for column in df.columns:
    if df[column].dtype == "object":
        count = df[column].astype(str).str.strip().isin(missing_like_values).sum()
         
        if count > 0:
            print(f"{column}:{count} missing values.")
    else:  
            print(f"🔍🧩✅  {column}: Doesn't contain any values from missing_values.")

🔍Main Info.
----------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 56244 entries, 0 to 56243
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   make                 56244 non-null  str
 1   model                56244 non-null  str
 2   priceUSD             56244 non-null  int64
 3   year                 56244 non-null  int64
 4   condition            56244 non-null  str
 5   mileage(kilometers)  56244 non-null  float64
 6   fuel_type            56244 non-null  str
 7   volume(cm3)          56197 non-null  float64
 8   color                56244 non-null  str
 9   transmission         56244 non-null  str
 10  drive_unit           54339 non-null  str
 11  segment              50953 non-null  str
dtypes: float64(2), int64(2), str(8)
memory usage: 5.1 MB
None
----------------------------------------
----Count Missing Values in dataset:
make                      0
model                     0
priceUSD                  0
year                      0
condition                 0
mileage(kilometers)       0
fuel_type                 0
volume(cm3)              47
color                     0
transmission              0
drive_unit             1905
segment                5291
dtype: int64
🔍🧩✅  make: Doesn't contain any values from missing_values.
🔍🧩✅  model: Doesn't contain any values from missing_values.
🔍🧩✅  priceUSD: Doesn't contain any values from missing_values.
🔍🧩✅  year: Doesn't contain any values from missing_values.
🔍🧩✅  condition: Doesn't contain any values from missing_values.
🔍🧩✅  mileage(kilometers): Doesn't contain any values from missing_values.
🔍🧩✅  fuel_type: Doesn't contain any values from missing_values.
🔍🧩✅  volume(cm3): Doesn't contain any values from missing_values.
🔍🧩✅  color: Doesn't contain any values from missing_values.
🔍🧩✅  transmission: Doesn't contain any values from missing_values.
🔍🧩✅  drive_unit: Doesn't contain any values from missing_values.
🔍🧩✅  segment: Doesn't contain any values from missing_values.

### 🔍 Main Info

* 📊 The dataset contains **56,244 rows and 12 columns**.
* 🔢 There are **4 numerical columns** and **8 categorical columns**.
* 🎯 The target variable is **price_usd**.
* ❌ **volume_cm3** contains **47 missing values**.
* ❌ **drive_unit** contains **1,905 missing values**.
* ❌ **segment** contains **5,291 missing values**.
* ✅ The remaining columns have **no missing values**.
* 💾 The dataset uses approximately **5.1 MB of memory**.

# 📋 Step 4: 
* 📊  Numerical columns
* 📊  Categorical columns

In [70]:
numeric_columns = [
    "priceUSD",
    "year",
    "mileage(kilometers)",
    "volume(cm3)"
]

categorical_columns = [
    "make",
    "model",
    "condition",
    "fuel_type",
    "color",
    "transmission",
    "drive_unit",
    "segment"
]
print(df[numeric_columns].dtypes)
print(df[numeric_columns].describe())

for column in categorical_columns:
    print(column)
    print(df[column].nunique())
    print("-" * 40)
    
    
for column in categorical_columns:
    print(column)
    print(df[column].value_counts(dropna=False))
    print("-" * 40)

priceUSD                 int64
year                     int64
mileage(kilometers)    float64
volume(cm3)            float64
dtype: object
            priceUSD          year  mileage(kilometers)   volume(cm3)
count   56244.000000  56244.000000         5.624400e+04  56197.000000
mean     7415.456440   2003.454840         2.443956e+05   2104.860615
std      8316.959261      8.144247         3.210307e+05    959.201633
min        48.000000   1910.000000         0.000000e+00    500.000000
25%      2350.000000   1998.000000         1.370000e+05   1600.000000
50%      5350.000000   2004.000000         2.285000e+05   1996.000000
75%      9807.500000   2010.000000         3.100000e+05   2300.000000
max    235235.000000   2019.000000         9.999999e+06  20000.000000
make
96
----------------------------------------
model
1034
----------------------------------------
condition
3
----------------------------------------
fuel_type
3
----------------------------------------
color
13
----------------------------------------
transmission
2
----------------------------------------
drive_unit
4
----------------------------------------
segment
9
----------------------------------------
make
make
volkswagen    6861
audi          4030
bmw           4013
opel          3779
renault       3713
              ...
trabant          1
jac              1
asia             1
tagaz            1
saipa            1
Name: count, Length: 96, dtype: int64
----------------------------------------
model
model
passat      2086
5-seriya    1476
a6          1276
golf        1070
astra       1013
            ...
xb             1
xc40           1
xjs            1
xt5            1
z3             1
Name: count, Length: 1034, dtype: int64
----------------------------------------
condition
condition
with mileage    55278
with damage       512
for parts         454
Name: count, dtype: int64
----------------------------------------
fuel_type
fuel_type
petrol        36405
diesel        19792
electrocar       47
Name: count, dtype: int64
----------------------------------------
color
color
black       12385
silver      10075
blue         8083
gray         5807
white        5292
green        3911
other        3397
red          2744
burgundy     2026
brown        1349
purple        625
yellow        317
orange        233
Name: count, dtype: int64
----------------------------------------
transmission
transmission
mechanics    36056
auto         20188
Name: count, dtype: int64
----------------------------------------
drive_unit
drive_unit
front-wheel drive             38016
rear drive                     6836
all-wheel drive                5890
part-time four-wheel drive     3597
NaN                            1905
Name: count, dtype: int64
----------------------------------------
segment
segment
D      12605
C      10617
J       8629
M       6313
E       6274
NaN     5291
B       4393
F        896
S        765
A        461
Name: count, dtype: int64
----------------------------------------

### Conclusion – Categorical Features 🧩


The categorical features contain different numbers of unique values. make has 96 unique values, while model has 1,034, indicating high cardinality. 
The other features have fewer categories: condition has 3, fuel_type 3, color 13, transmission 2, drive_unit 4, and segment 8 unique values, drive_unit and segment also contain missing values.
Current data types are appropriate for the dataset.
Further inspection in columns: priceUSD, mileage(kilometers), volume(cm), model...

# 📋 Step 5:
* 🎯 Target variable: priceUSD -- check values

In [71]:
print(df['priceUSD'].describe())

count     56244.000000
mean       7415.456440
std        8316.959261
min          48.000000
25%        2350.000000
50%        5350.000000
75%        9807.500000
max      235235.000000
Name: priceUSD, dtype: float64

⚠️ The maximum price of $235,235 is exceptionaly compared the median price of $5,350. 

This value should be investigated further to determine whether it represents a genuine high-priced vehicle or a potential outlier/data anomaly.

# 📋 Step 6: Info about priceUSD
* 📈 Data distribution and potential anomalies
* ⚠️ Extreme values and outliers

In [72]:
print("🔍🚗Car with the Highest Price.")
print(df.loc[df['priceUSD'].idxmax()])
print("-"*40)
print("🔍🚗Car with the lowest Price.")
print(df.loc[df['priceUSD'].idxmin()])

🔍🚗Car with the Highest Price.
make                           bentley
model                   continental-gt
priceUSD                        235235
year                              2018
condition                 with mileage
mileage(kilometers)            29000.0
fuel_type                       petrol
volume(cm3)                     6000.0
color                            white
transmission                      auto
drive_unit             all-wheel drive
segment                            NaN
Name: 20787, dtype: object
----------------------------------------
🔍🚗Car with the lowest Price.
make                           zaz
model                          968
priceUSD                        48
year                          1910
condition              with damage
mileage(kilometers)        25000.0
fuel_type                   petrol
volume(cm3)                 1100.0
color                        green
transmission             mechanics
drive_unit              rear drive
segment                          B
Name: 5952, dtype: object

### 🔎 Maximum Price Investigation

The highest price in the dataset is **$235,235**. After investigating the corresponding record, I found that it belongs to a **2018 Bentley Continental GT** with **29,000 km** mileage and a **6000 cm³** petrol engine.

The value appears to be plausible for this type of luxury vehicle, so it should not be automatically treated as an incorrect value. However, it represents an extreme value compared to most cars in the dataset and may influence the regression model.

### 🔎 Minimum Price Investigation

The minimum price is $48 for a damaged ZAZ 968. The year 1910 appears to be anomalous, but since the correct year cannot be confirmed with certainty, the original value will be retained for now.

# 📋 Step 7: Info about mileage(kilometers)
* 📈 Data distribution and potential anomalies
* ⚠️ Extreme values and outliers

In [73]:
print("🔍🚗Car with the Highest Mileage(kilometers).")
print(df.loc[df['mileage(kilometers)'].idxmax()])
print("-"*40)
print("🔍🚗Car with the lowest Mileage(kilometers).")
print(df.loc[df['mileage(kilometers)'].idxmin()])

🔍🚗Car with the Highest Mileage(kilometers).
make                                audi
model                                 80
priceUSD                             500
year                                1986
condition                   with mileage
mileage(kilometers)            9999999.0
fuel_type                         petrol
volume(cm3)                       1800.0
color                             silver
transmission                   mechanics
drive_unit             front-wheel drive
segment                                D
Name: 1394, dtype: object
----------------------------------------
🔍🚗Car with the lowest Mileage(kilometers).
make                               mazda
model                                  3
priceUSD                            5500
year                                2007
condition                   with mileage
mileage(kilometers)                  0.0
fuel_type                         petrol
volume(cm3)                       1600.0
color                             silver
transmission                   mechanics
drive_unit             front-wheel drive
segment                                C
Name: 184, dtype: object

### 🔍🚗 Mileage Analysis

* 🚨 **Highest mileage:** 9,999,999 km – Audi 80 (1986). This value appears to be an extreme data anomaly and should be investigated further.
* 🔍 **Lowest mileage:** 0 km – Mazda 3 (2007). This value may be valid, but it could also represent missing or unknown mileage and should be investigated.

🔍🚗 Further Investigation -------

* Count total anomaly values.
* Display anomaly rows.

In [74]:
print("Total number of rows with mileage in (9999999.0).")
print((df['mileage(kilometers)'] == 9999999.0).sum())
print("Total number of rows with mileage in (0.0)")
print((df['mileage(kilometers)'] == 0).sum())

Total number of rows with mileage in (9999999.0).
22
Total number of rows with mileage in (0.0)
190

In [75]:
print(df[df['mileage(kilometers)'] == 9999999.0])
print("-"*40)
print(df[df['mileage(kilometers)'] == 0])

                make     model  priceUSD  year     condition  \
1394            audi        80       500  1986  with mileage
1854            audi       100       900  1989  with mileage
5783         peugeot       806      4100  2000  with mileage
6114        lada-vaz      2104       600  1990  with mileage
6465        lada-vaz      2108       295  1990  with mileage
6684             raf      2203      1000  1991  with mileage
10032            bmw  5-seriya      2000  1985  with mileage
10316            bmw  7-seriya      4650  1998  with mileage
11699           audi        a4      3000  1996  with mileage
16705           fiat     brava      1100  1997  with mileage
21525          honda      cr-v      7300  2005  with mileage
23161  mercedes-benz   e-klass      1850  1989  with mileage
30631           opel    kadett       250  1985     for parts
31277        renault    laguna      1400  1995  with mileage
32444         nissan    laurel       550  1986  with mileage
36926           opel     omega       400  1987  with mileage
39466     volkswagen    passat       500  1987  with mileage
41166         nissan   primera       500  1993  with mileage
41315         nissan   primera       400  1991     for parts
46796           ford    sierra       143  1984     for parts
48019           fiat     stilo      3000  2001  with mileage
54172        citroen    xantia       879  1999  with mileage

       mileage(kilometers) fuel_type  volume(cm3)     color transmission  \
1394             9999999.0    petrol       1800.0    silver    mechanics
1854             9999999.0    petrol       2300.0     white    mechanics
5783             9999999.0    diesel       2000.0    silver    mechanics
6114             9999999.0    petrol       1500.0       red    mechanics
6465             9999999.0    petrol       1100.0       red    mechanics
6684             9999999.0    petrol       2400.0    yellow    mechanics
10032            9999999.0    petrol       2800.0      blue    mechanics
10316            9999999.0    petrol       3000.0     green         auto
11699            9999999.0    petrol       1800.0       red    mechanics
16705            9999999.0    petrol       1400.0     green    mechanics
21525            9999999.0    petrol       2400.0  burgundy         auto
23161            9999999.0    diesel       2000.0     black    mechanics
30631            9999999.0    petrol       1800.0       red    mechanics
31277            9999999.0    petrol       1800.0      blue    mechanics
32444            9999999.0    diesel       2800.0      gray    mechanics
36926            9999999.0    petrol       2000.0      blue    mechanics
39466            9999999.0    petrol       1800.0    purple    mechanics
41166            9999999.0    petrol       1600.0      blue    mechanics
41315            9999999.0    diesel       2000.0     other    mechanics
46796            9999999.0    petrol       1600.0     other    mechanics
48019            9999999.0    petrol       2400.0    silver         auto
54172            9999999.0    diesel       1900.0    silver    mechanics

                       drive_unit segment
1394            front-wheel drive       D
1854            front-wheel drive       E
5783            front-wheel drive       M
6114                   rear drive       B
6465            front-wheel drive       B
6684                   rear drive     NaN
10032                  rear drive       E
10316                  rear drive       F
11699           front-wheel drive       D
16705           front-wheel drive       C
21525  part-time four-wheel drive       J
23161                  rear drive       E
30631           front-wheel drive       C
31277           front-wheel drive       D
32444           front-wheel drive     NaN
36926                  rear drive       E
39466           front-wheel drive       D
41166           front-wheel drive       D
41315           front-wheel drive       D
46796                  rear drive     NaN
48019           front-wheel drive       C
54172           front-wheel drive       D
----------------------------------------
          make   model  priceUSD  year     condition  mileage(kilometers)  \
184      mazda       3      5500  2007  with mileage                  0.0
809    renault      19       209  1991     for parts                  0.0
863        gaz      21       999  1961  with mileage                  0.0
910    renault      21       500  1992  with mileage                  0.0
1009       uaz      31      1300  1994  with mileage                  0.0
...        ...     ...       ...   ...           ...                  ...
55084  citroen   xsara      1700  1999  with mileage                  0.0
55523   toyota   yaris      3400  2004  with mileage                  0.0
55638     opel  zafira      4450  2002  with mileage                  0.0
55711     opel  zafira      4100  2002  with mileage                  0.0
55795     opel  zafira      4400  2000  with mileage                  0.0

      fuel_type  volume(cm3)   color transmission                  drive_unit  \
184      petrol       1600.0  silver    mechanics           front-wheel drive
809      petrol       1700.0   brown    mechanics           front-wheel drive
863      petrol       2400.0    gray    mechanics           front-wheel drive
910      diesel       1900.0     red    mechanics           front-wheel drive
1009     petrol       2400.0    gray    mechanics  part-time four-wheel drive
...         ...          ...     ...          ...                         ...
55084    petrol       1800.0  silver    mechanics           front-wheel drive
55523    petrol       1000.0  silver    mechanics           front-wheel drive
55638    diesel       2000.0   black    mechanics           front-wheel drive
55711    diesel       2200.0    gray    mechanics           front-wheel drive
55795    petrol       1800.0   black    mechanics                         NaN

      segment
184         C
809         C
863         E
910         D
1009      NaN
...       ...
55084       C
55523       B
55638       M
55711       M
55795       M

[190 rows x 12 columns]

🔍🚗 Further Investigation – Extreme Mileage

After investigating all 22 vehicles with a mileage of 9,999,999 km, the value appears across different brands, models, years, prices, and vehicle conditions.
Since such a mileage value is unrealistic and occurs repeatedly across unrelated vehicles, it is most likely a placeholder or data entry anomaly rather than the actual mileage.
Therefore, these values should be treated as invalid mileage values during data preprocessing.

🔍🚗 Further Investigation – Zero Mileage

There are 190 vehicles with a mileage of 0 km. These values occur across different brands, models, years, and vehicle conditions.
Since zero mileage is unusual for used vehicles, these records require further investigation. However, there is not enough evidence to conclude that all of them are incorrect, so the values will be retained for now and considered during data preprocessing.

In [76]:
df[df['mileage(kilometers)'] == 0]['condition'].value_counts()

condition
with mileage    174
for parts        14
with damage       2
Name: count, dtype: int64

🔍🚗 Zero Mileage Conclusion

Among the 190 vehicles with 0 km mileage:

* 🚗 174 have the condition with mileage
* 🔧 14 have the condition for parts
* ⚠️ 2 have the condition with damage

The 174 vehicles listed as with mileage with 0 km are particularly unusual and may indicate missing or incorrectly recorded mileage. However, without reliable evidence of the actual mileage, these values will not be changed at this stage.

# 📋 Step 8:
* 🔍🚗 Volume(cm) analysis

In [77]:
df[df["volume(cm3)"] >= 10000][
    ["make", "model", "volume(cm3)","priceUSD"]
].sort_values("volume(cm3)", ascending=False)

          make model  volume(cm3)  priceUSD
81       mazda     3      20000.0      5300
354      mazda     6      20000.0      7500
1537      audi    80      20000.0      2900
1768      audi   100      20000.0      2150
4573   peugeot   407      20000.0      4600
...        ...   ...          ...       ...
3714     mazda   323      13000.0      1500
6338  lada-vaz  2106      13000.0      1236
6286  lada-vaz  2106      13000.0       530
6065  lada-vaz  2101      12000.0       214
6266  lada-vaz  2106      10000.0       618

[87 rows x 4 columns]

Conclusion

The volume(cm3) column contains several unrealistic values. Values between 10,000 and 20,000 cm³ are clearly suspicious for the car models in this dataset. Therefore, these values should be treated as invalid and replaced with NaN before further data preprocessing.

# 📋 Step 9:
* 🚗 Model Analysis

In [78]:

print(df['model'].value_counts())
print("-"*40)
print("The number of model unique categories:",df['model'].nunique())

model
passat      2086
5-seriya    1476
a6          1276
golf        1070
astra       1013
            ...
xb             1
xc40           1
xjs            1
xt5            1
z3             1
Name: count, Length: 1034, dtype: int64
----------------------------------------
The number of model unique categories: 1034

### 🚗 Model  Analysis Conclusion

The `model` column contains **1,034 unique categories**. Some models occur frequently, while others appear only once or a few times in the dataset.

This high cardinality should be considered during preprocessing, as applying One-Hot Encoding directly would create a large number of additional features.